grpc:
    host: "127.0.0.1"
    port: 8888
    enable: true

psql:
    provider: "postgres"
    username: "name"
    password: "pswd"
    host: "localhost"
    port: 5432
    dbname: dbname

issuer: "sausage"
secretkey: "32 byte key"

