// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	UserLogin string           `db:"user_login"`
	Uuid      string           `db:"uuid"`
	OtpHash   string           `db:"otp_hash"`
	OtpLink   string           `db:"otp_link"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
	Confirmed *bool            `db:"confirmed"`
}
