// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	//Confirmed
	//
	//  update users set confirmed = true where user_login = $1
	Confirmed(ctx context.Context, login *string) error
	//Hash
	//
	//  select otp_hash from users where user_login = $1
	Hash(ctx context.Context, login *string) (string, error)
	//IsConfirmed
	//
	//  select confirmed from users where user_login = $1
	IsConfirmed(ctx context.Context, login *string) (*bool, error)
	//Register
	//
	//  insert into users (user_login, uuid, otp_hash, otp_link, created_at) values ($1, gen_random_uuid(), $2, $3, now()) returning otp_hash
	Register(ctx context.Context, arg RegisterParams) (string, error)
}

var _ Querier = (*Queries)(nil)
