// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	//Confirmed
	//
	//  update users set confirmed = true where user_login = $1
	Confirmed(ctx context.Context, login *string) error
	//Hash
	//
	//  select otp_hash from users where user_login = $1
	Hash(ctx context.Context, login *string) (string, error)
	//IsExist
	//
	//  select exists(select 1 from users WHERE user_login = $1)
	IsExist(ctx context.Context, login *string) (bool, error)
	//Register
	//
	//  insert into users (user_login, uuid, otp_hash, otp_link, created_at, last_sign_up_at) values ($1, gen_random_uuid(), $2, $3, now(), now())
	Register(ctx context.Context, arg RegisterParams) error
}

var _ Querier = (*Queries)(nil)
