// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: register.sql

package db

import (
	"context"
)

const confirmed = `-- name: Confirmed :exec
update users set confirmed = true where user_login = $1
`

// Confirmed
//
//	update users set confirmed = true where user_login = $1
func (q *Queries) Confirmed(ctx context.Context, login *string) error {
	_, err := q.db.Exec(ctx, confirmed, login)
	return err
}

const hash = `-- name: Hash :one
select otp_hash from users where user_login = $1
`

// Hash
//
//	select otp_hash from users where user_login = $1
func (q *Queries) Hash(ctx context.Context, login *string) (string, error) {
	row := q.db.QueryRow(ctx, hash, login)
	var otp_hash string
	err := row.Scan(&otp_hash)
	return otp_hash, err
}

const isExist = `-- name: IsExist :one
select exists(select 1 from users WHERE user_login = $1)
`

// IsExist
//
//	select exists(select 1 from users WHERE user_login = $1)
func (q *Queries) IsExist(ctx context.Context, login *string) (bool, error) {
	row := q.db.QueryRow(ctx, isExist, login)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const register = `-- name: Register :exec
insert into users (user_login, uuid, otp_hash, otp_link, created_at, last_sign_up_at) values ($1, gen_random_uuid(), $2, $3, now(), now())
`

type RegisterParams struct {
	Login *string `db:"login"`
	Hash  *string `db:"hash"`
	Link  *string `db:"link"`
}

// Register
//
//	insert into users (user_login, uuid, otp_hash, otp_link, created_at, last_sign_up_at) values ($1, gen_random_uuid(), $2, $3, now(), now())
func (q *Queries) Register(ctx context.Context, arg RegisterParams) error {
	_, err := q.db.Exec(ctx, register, arg.Login, arg.Hash, arg.Link)
	return err
}
