// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRefreshToken = `-- name: GetRefreshToken :one
select refresh_hash, 
(expired_at <= now()) as is_expired, 
exists(select 1 from blacklist_refresh where refresh_hash = (select refresh_hash from users u where u.user_login = $1)) as block 
from users u where u.user_login = $1
`

type GetRefreshTokenRow struct {
	RefreshHash *string `db:"refresh_hash"`
	IsExpired   bool    `db:"is_expired"`
	Block       bool    `db:"block"`
}

// GetRefreshToken
//
//	select refresh_hash,
//	(expired_at <= now()) as is_expired,
//	exists(select 1 from blacklist_refresh where refresh_hash = (select refresh_hash from users u where u.user_login = $1)) as block
//	from users u where u.user_login = $1
func (q *Queries) GetRefreshToken(ctx context.Context, login *string) (GetRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, login)
	var i GetRefreshTokenRow
	err := row.Scan(&i.RefreshHash, &i.IsExpired, &i.Block)
	return i, err
}

const setBlockRefresh = `-- name: SetBlockRefresh :exec
insert into blacklist_refresh (refresh_hash) values ($1)
`

// SetBlockRefresh
//
//	insert into blacklist_refresh (refresh_hash) values ($1)
func (q *Queries) SetBlockRefresh(ctx context.Context, refreshHash *string) error {
	_, err := q.db.Exec(ctx, setBlockRefresh, refreshHash)
	return err
}

const setRefreshHash = `-- name: SetRefreshHash :exec
update users 
set refresh_hash = $1,
expired_at = $2
where user_login = $3
`

type SetRefreshHashParams struct {
	RefreshHash *string          `db:"refresh_hash"`
	ExpiredAt   pgtype.Timestamp `db:"expired_at"`
	Login       *string          `db:"login"`
}

// SetRefreshHash
//
//	update users
//	set refresh_hash = $1,
//	expired_at = $2
//	where user_login = $3
func (q *Queries) SetRefreshHash(ctx context.Context, arg SetRefreshHashParams) error {
	_, err := q.db.Exec(ctx, setRefreshHash, arg.RefreshHash, arg.ExpiredAt, arg.Login)
	return err
}
