// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: docs/proto/v1/auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AcceptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	OtpCode       string                 `protobuf:"bytes,2,opt,name=otp_code,json=otpCode,proto3" json:"otp_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRequest) Reset() {
	*x = AcceptRequest{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRequest) ProtoMessage() {}

func (x *AcceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRequest.ProtoReflect.Descriptor instead.
func (*AcceptRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AcceptRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AcceptRequest) GetOtpCode() string {
	if x != nil {
		return x.OtpCode
	}
	return ""
}

type AcceptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptResponse) Reset() {
	*x = AcceptResponse{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptResponse) ProtoMessage() {}

func (x *AcceptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptResponse.ProtoReflect.Descriptor instead.
func (*AcceptResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_docs_proto_v1_auth_proto protoreflect.FileDescriptor

const file_docs_proto_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x18docs/proto/v1/auth.proto\x12\aauth.v1\"'\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\"$\n" +
	"\x10RegisterResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"@\n" +
	"\rAcceptRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x19\n" +
	"\botp_code\x18\x02 \x01(\tR\aotpCode\"(\n" +
	"\x0eAcceptResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x8a\x01\n" +
	"\vAuthService\x12?\n" +
	"\bRegister\x12\x18.auth.v1.RegisterRequest\x1a\x19.auth.v1.RegisterResponse\x12:\n" +
	"\aConfirm\x12\x16.auth.v1.AcceptRequest\x1a\x17.auth.v1.AcceptResponseB=Z;github.com/RenterRus/sausage-profile/auth/pb/auth/v1;authpbb\x06proto3"

var (
	file_docs_proto_v1_auth_proto_rawDescOnce sync.Once
	file_docs_proto_v1_auth_proto_rawDescData []byte
)

func file_docs_proto_v1_auth_proto_rawDescGZIP() []byte {
	file_docs_proto_v1_auth_proto_rawDescOnce.Do(func() {
		file_docs_proto_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docs_proto_v1_auth_proto_rawDesc), len(file_docs_proto_v1_auth_proto_rawDesc)))
	})
	return file_docs_proto_v1_auth_proto_rawDescData
}

var file_docs_proto_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_docs_proto_v1_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: auth.v1.RegisterRequest
	(*RegisterResponse)(nil), // 1: auth.v1.RegisterResponse
	(*AcceptRequest)(nil),    // 2: auth.v1.AcceptRequest
	(*AcceptResponse)(nil),   // 3: auth.v1.AcceptResponse
}
var file_docs_proto_v1_auth_proto_depIdxs = []int32{
	0, // 0: auth.v1.AuthService.Register:input_type -> auth.v1.RegisterRequest
	2, // 1: auth.v1.AuthService.Confirm:input_type -> auth.v1.AcceptRequest
	1, // 2: auth.v1.AuthService.Register:output_type -> auth.v1.RegisterResponse
	3, // 3: auth.v1.AuthService.Confirm:output_type -> auth.v1.AcceptResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_docs_proto_v1_auth_proto_init() }
func file_docs_proto_v1_auth_proto_init() {
	if File_docs_proto_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docs_proto_v1_auth_proto_rawDesc), len(file_docs_proto_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docs_proto_v1_auth_proto_goTypes,
		DependencyIndexes: file_docs_proto_v1_auth_proto_depIdxs,
		MessageInfos:      file_docs_proto_v1_auth_proto_msgTypes,
	}.Build()
	File_docs_proto_v1_auth_proto = out.File
	file_docs_proto_v1_auth_proto_goTypes = nil
	file_docs_proto_v1_auth_proto_depIdxs = nil
}
